# Generated by Django 4.2.7 on 2025-07-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='College',
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'Colleges'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='faculty',
            new_name='college',
        ),
        migrations.AlterModelTable(
            name='college',
            table='colleges',
        ),
    ]
