# Generated by Django 4.2.7 on 2025-07-19 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_rename_faculty_college_alter_college_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('physical', 'Physical Room'), ('virtual', 'Virtual Room')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('facilities', models.TextField(blank=True)),
                ('virtual_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('other', 'Other')], max_length=20)),
                ('default_meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='venue',
            new_name='custom_location',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='virtual_link',
            new_name='meeting_link',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='requested_at',
            new_name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='classsession',
            name='attendance_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'Face Recognition'), ('both', 'Both Methods')], default='face_recognition', max_length=20),
        ),
        migrations.AddField(
            model_name='classsession',
            name='attendance_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_passcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='courses.classsession'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='classsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='class_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('practical', 'Practical'), ('seminar', 'Seminar'), ('exam', 'Examination')], default='lecture', max_length=20),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='recurrence_pattern',
            field=models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['scheduled_date', 'start_time'], name='class_sessi_schedul_4c2acd_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['course_assignment', 'scheduled_date'], name='class_sessi_course__ec42ef_idx'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='courses.room'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['room', 'scheduled_date'], name='class_sessi_room_id_85e34c_idx'),
        ),
    ]
